# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests using node 21.7
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
          node-version: "21.7"
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint
      - run: npm run test
